name: Test and Publish SNMP::Info
on:
  workflow_dispatch:
    inputs:
      success_irc_squawk:
        description: 'Squawk to IRC on successful tests'
        required: false
        default:  false
      debug_test_enabled:
        description: 'With build and test debug'
        required: false
        default:  false
  # push:
  #   branches:
  #     - master
  #   tags:
  #     - '[0-9].[0-9][0-9][0-9]?[0-9]?[0-9]?[0-9]?'
  # pull_request:
  #   types: [opened, synchronize, reopened]
jobs:
  test_snmp_info:
    name: Test and CPAN Upload
    #if: github.repository == 'netdisco/snmp-info'
    runs-on: ubuntu-latest
    container:
      image: 'netdisco/netdisco:latest-do'
      options: '--user root --entrypoint /bin/ash'
      volumes:
        - '/home/runner/work:/github/workspace'
    defaults:
      run:
        working-directory: /github/workspace/snmp-info/snmp-info
    steps:
    - name: Get the Tag or Branch
      run: echo "GH_REF_SHORT=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

    - name: Install base packages
      run: apk add tmux bash curl sudo xz
    - name: Install other packages
      run: apk add openssh-client gcc make musl-dev perl-dev unzip jq
    - name: Install fake apt-get
      run: echo 'if [ "$1" == "update" ]; then exec apk update; else exec apk add openssh-client xz; fi' > /usr/local/bin/apt-get && chmod +x /usr/local/bin/apt-get

    - name: Check out latest code
      uses: actions/checkout@v1
    - name: Fix owner of checkout
      run: chown -R netdisco:netdisco /github/workspace/snmp-info/snmp-info

    - name: Download latest netdisco-mibs
      working-directory: /home/netdisco/netdisco-mibs
      run: |
        rm -rf /home/netdisco/netdisco-mibs/* && 
        curl -sL https://api.github.com/repos/netdisco/netdisco-mibs/releases/latest |
          grep browser_download_url | xargs printf "curl -sL %s\n" | tail -1 |
          sh | tar --strip-components=1 -zxf - &&
        chown -R netdisco:netdisco /home/netdisco/netdisco-mibs

    - name: Install Perl deps
      run: |
        sudo -u netdisco /home/netdisco/bin/localenv cpanm --notest Hook::LexWrap Test::Class::Most Test::Distribution Test::MockObject::Extends PPI Class::ISA Module::Info File::Slurp Test::Perl::Critic Test::Spelling CPAN::Uploader

    - name: Run Tests
      id: build_and_run_tests
      run: |
        sudo -u netdisco /home/netdisco/bin/localenv perl ./Build.PL
        sudo -u netdisco /home/netdisco/bin/localenv ./Build test --test_files t/ --test_files xt/
      continue-on-error: true


